export const REPOSITORY_LIST = {
  edges: [
    {
      node: {
        id: 'jaredpalmer.formik',
        fullName: 'jaredpalmer/formik',
        description: 'Build forms in React, without the tears 😭 ',
        language: 'TypeScript',
        stargazersCount: 25835,
        forksCount: 2085,
        reviewCount: 5,
        ratingAverage: 90,
        ownerAvatarUrl: 'https://avatars0.githubusercontent.com/u/50745844?v=4',
        __typename: 'Repository',
      },
      __typename: 'RepositoryEdge',
    },
    {
      node: {
        id: 'async-library.react-async',
        fullName: 'async-library/react-async',
        description: '🍾 Flexible promise-based React data loader',
        language: 'JavaScript',
        stargazersCount: 1907,
        forksCount: 80,
        reviewCount: 3,
        ratingAverage: 72,
        ownerAvatarUrl: 'https://avatars1.githubusercontent.com/u/54310907?v=4',
        __typename: 'Repository',
      },
      __typename: 'RepositoryEdge',
    },
    {
      node: {
        id: 'rzwitserloot.lombok',
        fullName: 'rzwitserloot/lombok',
        description: 'Very spicy additions to the Java programming language.',
        language: 'Java',
        stargazersCount: 9891,
        forksCount: 1898,
        reviewCount: 0,
        ratingAverage: 0,
        ownerAvatarUrl: 'https://avatars3.githubusercontent.com/u/93303?v=4',
        __typename: 'Repository',
      },
      __typename: 'RepositoryEdge',
    },
    {
      node: {
        id: 'rails.rails',
        fullName: 'rails/rails',
        description: 'Ruby on Rails',
        language: 'Ruby',
        stargazersCount: 47345,
        forksCount: 18992,
        reviewCount: 2,
        ratingAverage: 100,
        ownerAvatarUrl: 'https://avatars1.githubusercontent.com/u/4223?v=4',
        __typename: 'Repository',
      },
      __typename: 'RepositoryEdge',
    },
    {
      node: {
        id: 'django.django',
        fullName: 'django/django',
        description: 'The Web framework for perfectionists with deadlines.',
        language: 'Python',
        stargazersCount: 54760,
        forksCount: 23505,
        reviewCount: 2,
        ratingAverage: 73,
        ownerAvatarUrl: 'https://avatars2.githubusercontent.com/u/27804?v=4',
        __typename: 'Repository',
      },
      __typename: 'RepositoryEdge',
    },
    {
      node: {
        id: 'apollographql.apollo-client',
        fullName: 'apollographql/apollo-client',
        description:
          ':rocket: A fully-featured, production ready caching GraphQL client for every UI framework and GraphQL server',
        language: 'TypeScript',
        stargazersCount: 15340,
        forksCount: 1976,
        reviewCount: 0,
        ratingAverage: 0,
        ownerAvatarUrl: 'https://avatars0.githubusercontent.com/u/17189275?v=4',
        __typename: 'Repository',
      },
      __typename: 'RepositoryEdge',
    },
    {
      node: {
        id: 'reduxjs.redux',
        fullName: 'reduxjs/redux',
        description: 'Predictable state container for JavaScript apps',
        language: 'TypeScript',
        stargazersCount: 55026,
        forksCount: 14509,
        reviewCount: 0,
        ratingAverage: 0,
        ownerAvatarUrl: 'https://avatars3.githubusercontent.com/u/13142323?v=4',
        __typename: 'Repository',
      },
      __typename: 'RepositoryEdge',
    },
    {
      node: {
        id: 'spring-projects.spring-framework',
        fullName: 'spring-projects/spring-framework',
        description: 'Spring Framework',
        language: 'Java',
        stargazersCount: 40921,
        forksCount: 28303,
        reviewCount: 0,
        ratingAverage: 0,
        ownerAvatarUrl: 'https://avatars0.githubusercontent.com/u/317776?v=4',
        __typename: 'Repository',
      },
      __typename: 'RepositoryEdge',
    },
    {
      node: {
        id: 'zeit.next.js',
        fullName: 'zeit/next.js',
        description: 'The React Framework',
        language: 'JavaScript',
        stargazersCount: 59668,
        forksCount: 10304,
        reviewCount: 0,
        ratingAverage: 0,
        ownerAvatarUrl: 'https://avatars0.githubusercontent.com/u/14985020?v=4',
        __typename: 'Repository',
      },
      __typename: 'RepositoryEdge',
    },
    {
      node: {
        id: 'zeit.swr',
        fullName: 'zeit/swr',
        description: 'React Hooks library for remote data fetching',
        language: 'TypeScript',
        stargazersCount: 15002,
        forksCount: 502,
        reviewCount: 0,
        ratingAverage: 0,
        ownerAvatarUrl: 'https://avatars0.githubusercontent.com/u/14985020?v=4',
        __typename: 'Repository',
      },
      __typename: 'RepositoryEdge',
    },
  ],
  __typename: 'RepositoryConnection',
};
